config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :controls
  resources :assets
  resources :scopes
  resources :organizations, only: %i[new create show edit update]
  root 'home#index'
  get 'box/c/:control_id/a/:asset_id', to: 'boxes#show', as: :box
  get 'login', to: 'logins#new'
  get 'login/create', to: 'logins#create', as: :create_login
  get 'logout', to: 'logouts#new'
end

app/models/control.rb
# == Schema Information
#
# Table name: controls
#
#  id              :uuid             not null, primary key
#  description     :text
#  handle          :string
#  name            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organization_id :uuid             not null
#
# Indexes
#
#  index_controls_on_organization_id  (organization_id)
#
# Foreign Keys
#
#  fk_rails_...  (organization_id => organizations.id)
#
class Control < ApplicationRecord
  belongs_to :organization
  validates_presence_of :handle, :name, :organization
  has_many :control_scopes
  has_many :scopes, through: :control_scopes
  has_many :artifacts

  def assets
    assets = []
    scopes.each { |s| assets = assets + s.assets }
    assets.uniq(&:id)
  end
end

app/controllers/controls_controller.rb
class ControlsController < AuthorizationController
  before_action :set_control, only: %i[show edit update destroy]
  before_action :set_organization # GET /controls.json
  def index
    @controls = @organization.controls.all
    @current_user = current_user
  end

  # GET /controls/1
  # GET /controls/1.json
  def show; end

  # GET /controls/new
  def new
    @control = Control.new organization: @organization
  end

  # GET /controls/1/edit
  def edit; end

  # POST /controls
  # POST /controls.json
  def create
    @control = Control.new(control_params)
    @control.organization = @organization
    respond_to do |format|
      if @control.save
        format.html do
          redirect_to @control, notice: 'Control was successfully created.'
        end
        format.json { render :show, status: :created, location: @control }
      else
        format.html { render :new }
        format.json do
          render json: @control.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /controls/1
  # PATCH/PUT /controls/1.json
  def update
    respond_to do |format|
      if @control.update(control_params)
        format.html do
          redirect_to @control, notice: 'Control was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @control }
      else
        format.html { render :edit }
        format.json do
          render json: @control.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /controls/1
  # DELETE /controls/1.json
  def destroy
    @control.destroy
    respond_to do |format|
      format.html do
        redirect_to controls_url, notice: 'Control was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private # Use callbacks to share common setup or constraints between actions.
  def set_control
    @control = Control.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def control_params
    params.fetch(:control, {}).permit(:name, :handle, :description)
  end

  def set_organization
    @organization = Organization.first
  end
end

app/helpers/controls_helper.rb
module ControlsHelper; end

app/views/controls/_form.html.erb
<%= form_with(model: control, local: true) do |form| %>
  <% if control.errors.any? %>
    <div id="error_explanation" class="error-box">
      <h2 class="error-box__title"><%= pluralize(control.errors.count, "error") %> prohibited this control from being saved:</h2>

      <ul class="error-box__list">
        <% control.errors.full_messages.each do |message| %>
          <li class="error-box__list-item"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="stack-v">
    <div class="form-group">
      <%= label_tag :name, 'Name', class: 'form-group__label' %>
      <%= form.text_field :name, class: 'form-input' %>
    </div>

    <div>
      <%= label_tag :handle, 'Handle', class: 'form-group__label' %>
      <%= form.text_field :handle, class: 'form-input' %>
    </div>

    <div>
      <%= label_tag :description, 'Description', class: 'form-group__label' %>
      <%= form.text_area :description, class: 'form-input' %>
    </div>

    <div class="form-group__actions">
      <%= form.submit class: 'btn-primary form-group__action_item' %>
      <%= link_to 'Cancel', controls_path, class: 'btn-ghost form-group__action_item' %>    
    </div>
  </div>
<% end %>

app/views/controls/edit.html.erb
<div class="page-form">
  <div class="page-form__intro">
    <h1 class="text-white text-2xl mt-12">Edit <%= @control.name %></h1>
    
  </div>
  <%= render 'form', control: @control %>
</div>

app/views/controls/index.html.erb
<p id="notice" class="success-box"><%= notice %></p>

<div class="page-header">
  <div class="page-header__title">
    <h1 class="text-white text-2xl">Controls</h1>
  </div>
  <div class="page-header__actions">  
    <%= link_to 'New Control', new_control_path, class: 'btn-primary' %>
  </div>
</div>

<%= render partial: 'components/control_list', locals: { controls: @controls } %>

app/views/controls/new.html.erb
<p id="notice" class="success-box"><%= notice %></p>

<div class="page-form">
  <div class="page-form__intro">
    <h1 class="text-white text-2xl mt-12">Create a Control</h1>
    <p>Controls represent the safeguards or security measures implemented by your organization.
    Controls in Auditbox can map to the assets in your inventory making it easy to ensure you
    have evidence in place for all assets governed by this control.</p> 

    <p>Learn more about <a href="https://docs.auditbox.dev">control scoping and evidence collection.</a></p>
  </div>
  <%= render 'form', control: @control %>
</div>

app/views/controls/show.html.erb
<p id="notice" class="success-box"><%= notice %></p>


<div class="page-header border-b-0">
  <div class="page-header__title">
    <%= link_to '← Controls', controls_path, class: 'text-sm text-purple-700 inline-block mb-3' %>
    <h1 class="text-white text-2xl"><%= "#{@control.handle} - #{@control.name}" %></h1>
    <p class=""><%= @control.description %></p>
  </div>
  <div class="page-header__actions">
    <%= link_to 'Edit', edit_control_path(@control), class: 'btn-ghost' %>
    <%= link_to 'Destroy', @control, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-ghost' %>
  </div>
</div>


<% @control.scopes.each do |scope| %>
<div class="">
  <h2 class="mb-4"><%= scope.name %></h2>
  <div class="mb-4">
    <%= pluralize(scope.assets.count, 'asset') %>: matching the tags <% scope.tags.each do |key, value| %>
      <span class="tag__key"><%= key %></span><span class="tag__value"><%= value %></span>
    <% end %>
  </div>

  <div class="resource-list">
    
    <% scope.assets.each do |asset| %>
      <div class="resource-list-item">
        <div class="resource-list-item__main">
          <div class="resource-list-item__name">
            <%= asset.handle %>
          </div>
        </div>
        <div class="resource-list-item__scope text-right">
          <% artifacts = asset.artifacts.where(control: @control) %> 
          <%= link_to pluralize(artifacts.count, 'evidence artifact'), box_url(control_id: @control.id, asset_id: asset.id) %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% end %>