config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :controls
  resources :assets
  resources :scopes
  resources :organizations, only: %i[new create show edit update]
  root 'home#index'
  get 'box/c/:control_id/a/:asset_id', to: 'boxes#show', as: :box
  get 'login', to: 'logins#new'
  get 'login/create', to: 'logins#create', as: :create_login
  get 'logout', to: 'logouts#new'
end

app/models/scope.rb
# == Schema Information
#
# Table name: scopes
#
#  id              :uuid             not null, primary key
#  name            :string           not null
#  tags            :text             default([]), is an Array
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organization_id :uuid             not null
#
# Indexes
#
#  index_scopes_on_name_and_organization_id  (name,organization_id) UNIQUE
#  index_scopes_on_organization_id           (organization_id)
#
# Foreign Keys
#
#  fk_rails_...  (organization_id => organizations.id)
#
class Scope < ApplicationRecord
  belongs_to :organization
  validates_presence_of :name, :organization
  has_many :control_scopes
  has_many :controls, through: :control_scopes

  def assets
    return [] if tags.empty?
    query = organization.assets #tags = [['environment', 'production'], ['containsPHI', true]]

    tags.each do |tag|
      key, value = tag
      query =
        query.where('tags ->> :key = :value', key: key.to_s, value: value.to_s)
    end
    query
  end
end

app/controllers/scopes_controller.rb
class ScopesController < AuthorizationController
  before_action :set_scope, only: %i[show edit update destroy]
  before_action :set_organization # GET /scopes.json
  def index
    @scopes = @organization.scopes.all
  end

  # GET /scopes/1
  # GET /scopes/1.json
  def show; end

  # GET /scopes/new
  def new
    @scope = Scope.new organization: @organization
  end

  # GET /scopes/1/edit
  def edit; end

  # POST /scopes
  # POST /scopes.json
  def create
    @scope = Scope.new(scope_params)
    @scope.organization = @organization
    respond_to do |format|
      if @scope.save
        format.html do
          redirect_to @scope, notice: 'Scope was successfully created.'
        end
        format.json { render :show, status: :created, location: @scope }
      else
        format.html { render :new }
        format.json do
          render json: @scope.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /scopes/1
  # PATCH/PUT /scopes/1.json
  def update
    respond_to do |format|
      if @scope.update(scope_params)
        format.html do
          redirect_to @scope, notice: 'Scope was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @scope }
      else
        format.html { render :edit }
        format.json do
          render json: @scope.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /scopes/1
  # DELETE /scopes/1.json
  def destroy
    @scope.destroy
    respond_to do |format|
      format.html do
        redirect_to assets_url, notice: 'Scope was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private # Use callbacks to share common setup or constraints between actions.
  def set_scope
    @scope = Scope.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def scope_params
    params.fetch(:scope, {}).permit(:name, :handle, :description)
  end

  def set_organization
    @organization = Organization.first
  end
end

app/views/scopes/_form.html.erb
<%= form_with(model: scope, local: true) do |form| %>
  <% if scope.errors.any? %>
    <div id="error_explanation" class="error-box">
      <h2 class="error-box__title"><%= pluralize(scope.errors.count, "error") %> prohibited this scope from being saved:</h2>

      <ul class="error-box__list">
        <% scope.errors.full_messages.each do |message| %>
          <li class="error-box__list-item"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="stack-v">
    <div class="form-group">
      <%= label_tag :name, 'Name', class: 'form-group__label' %>
      <%= form.text_field :name, class: 'form-input', placeholder: 'e.g. Production Databases under HIPAA' %>
    </div>

    <div class="form-group">
      <label class="form-group__label">Asset tags</label>
      <div class="stack-v">
        <div class="flex flex-row -mx-2">
          <div class="w-1/2">
            <div class="px-2">
              <%= label_tag :tag1_key, 'Tag 1 Key', class: 'form-group__label' %>
              <%= form.text_field :tag1_key, class: 'form-input', placeholder: 'e.g. environment' %>
            </div>
          </div>
          <div class="w-1/2">
            <div class="px-2">
              <%= label_tag :tag1_value, 'Tag 1 Value', class: 'form-group__label' %>
              <%= form.text_field :tag1_value, class: 'form-input', placeholder: 'e.g. production' %>
            </div>
          </div>
        </div>

        <div class="flex flex-row -mx-2">
          <div class="w-1/2">
            <div class="px-2">
              <%= label_tag :tag2_key, 'Tag 2 Key', class: 'form-group__label' %>
              <%= form.text_field :tag2_key, class: 'form-input', placeholder: 'e.g. contains-phi' %>
            </div>
          </div>
          <div class="w-1/2">
            <div class="px-2">
              <%= label_tag :tag1_value, 'Tag 2 Value', class: 'form-group__label' %>
              <%= form.text_field :tag2_value, class: 'form-input', placeholder: 'e.g. true'%>
            </div>
          </div>
        </div>

        <div class="flex flex-row -mx-2">
          <div class="w-1/2">
            <div class="px-2">
              <%= label_tag :tag1_key, 'Tag 3 Key', class: 'form-group__label' %>
              <%= form.text_field :tag1_key, class: 'form-input' %>
            </div>
          </div>
          <div class="w-1/2">
            <div class="px-2">
              <%= label_tag :tag1_value, 'Tag 3 Value', class: 'form-group__label' %>
              <%= form.text_field :tag1_value, class: 'form-input' %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="form-group__actions">
      <%= form.submit class: 'btn-primary form-group__action_item' %>
      <%= link_to 'Cancel', assets_path, class: 'btn-ghost form-group__action_item' %>    
    </div>
  </div>
<% end %>

app/views/scopes/new.html.erb
<p id="notice" class="success-box"><%= notice %></p>

<div class="page-form">
  <div class="page-form__intro">
    <h1 class="text-white text-2xl mt-12">Create an Asset Scope</h1>
    <p>Scopes help you divide your asset inventory into groupings that can
    then be monitored by controls for evidence. For example, if you have an encyrption at-rest
    control, you may wish to limit evidence collection to just the apps and
    databases that store or process PHI.</p> 

    <p>Note: assets are filtered using AND and not OR. If your scope matches on environment=staging and containsPHI=true then only
    those assets that match both tags will be included in the scope.</p>

    <p>Learn more about <a href="https://docs.auditbox.dev">scoping assets to controls.</a></p>
  </div>
  <%= render 'form', scope: @scope %>
</div>