config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :controls
  resources :assets
  resources :scopes
  resources :organizations, only: %i[new create show edit update]
  root 'home#index'
  get 'box/c/:control_id/a/:asset_id', to: 'boxes#show', as: :box
  get 'login', to: 'logins#new'
  get 'login/create', to: 'logins#create', as: :create_login
  get 'logout', to: 'logouts#new'
end

app/models/asset.rb
# == Schema Information
#
# Table name: assets
#
#  id              :uuid             not null, primary key
#  asset_type      :string
#  handle          :string
#  props           :jsonb            not null
#  tags            :jsonb            not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organization_id :uuid             not null
#
# Indexes
#
#  index_assets_on_organization_id  (organization_id)
#
# Foreign Keys
#
#  fk_rails_...  (organization_id => organizations.id)
#
class Asset < ApplicationRecord
  belongs_to :organization
  validates_presence_of :handle, :asset_type, :organization
  has_many :artifacts
  before_validation :serialize_hashes

  def serialize_hashes
    self.props = JSON.parse props if props.kind_of? String
    self.tags = JSON.parse tags if tags.kind_of? String
  end

  def artifacts_for_control(control)
    artifacts.where(control: control)
  end
end

app/controllers/assets_controller.rb
class AssetsController < AuthorizationController
  before_action :set_asset, only: %i[show edit update destroy]
  before_action :set_organization # GET /assets.json
  def index
    @scopes = @organization.scopes.all
    @scope = Scope.find params[:scope] if params[:scope]

    @assets = @scope.assets if @scope
    @assets = @organization.assets.all unless @scope
  end

  # GET /assets/1
  # GET /assets/1.json
  def show; end

  # GET /assets/new
  def new
    @asset = Asset.new organization: @organization
  end

  # GET /assets/1/edit
  def edit; end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(asset_params)
    @asset.organization = @organization

    respond_to do |format|
      if @asset.save
        format.html do
          redirect_to assets_path, notice: 'Asset was successfully created.'
        end
        format.json { render :show, status: :created, location: @asset }
      else
        format.html { render :new }
        format.json do
          render json: @asset.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html do
          redirect_to @asset, notice: 'Asset was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit }
        format.json do
          render json: @asset.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html do
        redirect_to assets_url, notice: 'Asset was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private # Use callbacks to share common setup or constraints between actions.
  def set_asset
    @asset = Asset.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def asset_params
    params.fetch(:asset, {}).permit(:handle, :asset_type, :props, :tags)
  end

  def set_organization
    @organization = Organization.first
  end
end

app/helpers/assets_helper.rb
module AssetsHelper; end

app/views/assets/_form.html.erb
<%= form_with(model: asset, local: true) do |form| %>
  <% if asset.errors.any? %>
    <div id="error_explanation" class="error-box">
      <h2 class="error-box__title"><%= pluralize(asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul class="error-box__list">
        <% asset.errors.full_messages.each do |message| %>
          <li class="error-box__list-item"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="stack-v">
    <div class="form-group">
      <%= label_tag :handle, 'Handle', class: 'form-group__label' %>
      <div class="form-label-description">Handles must be unique. Consider using the unique identify from this asset's source of truth (such ARN for AWS resources).</div>
      <%= form.text_field :handle, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= label_tag :asset_type, 'Type', class: 'form-group__label' %>
      <%= form.text_field :asset_type, class: 'form-input', placeholder: 'e.g. Database or 3rd Party Webservice' %>
    </div>

    <div class="form-group">
      <%= label_tag :props, 'Attributes', class: 'form-group__label' %>
      <div class="form-label-description">Whatever you input here will be parsed as JSON.</div>
      <%= form.text_area :props, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= label_tag :tags, 'Tags', class: 'form-group__label' %>
      <div class="form-label-description">Whatever you input here will be parsed as JSON.</div>
      <%= form.text_area :tags, class: 'form-input' %>
    </div>

    <div class="form-group__actions">
      <%= form.submit class: 'btn-primary form-group__action-item' %>
      <%= link_to 'Cancel', assets_path, class: 'btn-ghost form-group__action_item' %>
    </div>
  </div>
<% end %>

app/views/assets/edit.html.erb
<div class="page-form">
  <div class="page-form__intro">
    <h1 class="text-white text-2xl mt-12">Edit <%= @asset.handle %></h1>
    
  </div>
  <%= render 'form', asset: @asset %>
</div>

app/views/assets/index.html.erb
<p id="notice" class="success-box"><%= notice %></p>

<div class="page-header">
  <div class="page-header__title">
    <h1 class="text-white text-2xl">Assets</h1>
  </div>
  <div class="page-header__actions">  
    <%= link_to 'New Asset', new_asset_path, class: 'btn-primary' %>
  </div>
</div>


<div class="flex mb-4">
  <div class="w-1/4">
    <div class="pr-8">
      <h4 class="font-semibold mb-3">Asset Scopes</h4>
      <ul class="nav-list">
        <%
          currentCn = "nav-list__item--active"
        %>
        <li class="nav-list__item <%= currentCn unless @scope%>">
          <%= link_to 'All Assets', assets_path, class: 'nav-list__item-link' %>
        </li>
        <% @scopes.each do |scope| %>
          <li class="nav-list__item <%= currentCn if (@scope && @scope == scope) %>">
            <%= link_to scope.name, assets_path(scope: scope), class: 'nav-list__item-link' %>
          </li>
        <% end %>

        <li class="border-purple-800 border-t pt-3 mt-3">
          <%= link_to 'New Scope', new_scope_path %>
        </li>
      </ul>
    </div>
  </div>

  <div class="w-3/4">
    <h4 class="font-semibold mb-6">
      <%= @scope ? @scope.name : 'All Assets' %> (<%= pluralize @assets.count, 'asset' %>)
    </h4>
    <%= render partial: 'components/asset_list', locals: { assets: @assets } %>
  </div>
</div>

app/views/assets/new.html.erb
<div class="page-form">
  <div class="page-form__intro">
    <h1 class="text-white text-2xl mt-12">Create an Asset</h1>
    <p>Assets are the resources that comprising your organization
    that are worth protecting. Assets can be anything from empoyees and roles to apps and databases.</p>

    <p>Check out the Auditbox SDK documentation for bulk asset import examples</p>
  </div> 
  <%= render 'form', asset: @asset %>
</div>

app/views/assets/show.html.erb
<p id="notice" class="success-box"><%= notice %></p>


<div class="page-header border-b-0">
  <div class="page-header__title">
    <%= link_to '← Assets', assets_path, class: 'text-sm text-purple-700 inline-block mb-3' %>
    <h1 class="text-white text-2xl"><%= @asset.handle %></h1>
  </div>
  <div class="page-header__actions">
    <%= link_to 'Edit', edit_asset_path(@asset), class: 'btn-ghost' %> 
    <%= link_to 'Destroy', @asset, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-ghost' %>
  </div>
</div>

<div class="flex mb-4 -mx-2">
  <div class="w-3/4 px-2">
    <div>
    <h1 class="text-white text-2xl">Evidence</h1>
    </div>
  </div>
  <div class="w-1/4 px-2">
    <div class="rounded">
      <h1 class="text-white text-2xl">Properties</h1>
      <%= link_to 'Edit', edit_asset_path(@asset) %>
      <div class="stack-v">
        <div>
          <div>Handle</div>
          <div><%= @asset.handle %>
        </div>

        <div>
          <div>Type</div>
          <div><%= @asset.asset_type %>
        </div>
        
        <% @asset.props.each do |prop, value| %>
          <div>
          <div><%= prop.capitalize %></div>
          <div><%= value %>
          </div>
        <% end %>

        <% @asset.tags.each do |tag, value| %>
          <div class="tag">
            <div><%= tag.capitalize %></div>
            <div><%= value %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

Evidence
Governing Controls
Properties