config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :controls
  resources :assets
  resources :scopes
  resources :organizations, only: %i[new create show edit update]
  root 'home#index'
  get 'box/c/:control_id/a/:asset_id', to: 'boxes#show', as: :box
  get 'login', to: 'logins#new'
  get 'login/create', to: 'logins#create', as: :create_login
  get 'logout', to: 'logouts#new'
end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id         :uuid             not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Organization < ApplicationRecord
  validates_presence_of :name
  has_many :controls
  has_many :assets
  has_many :tags
  has_many :scopes
end

app/controllers/organizations_controller.rb
class OrganizationsController < AuthorizationController
  before_action :set_organization, only: %i[show edit update destroy]
  skip_before_action :require_organization, only: %i[new create] # GET /organizations/1.json
  def show; end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit; end

  # POST /organizations
  # POST /organizations.json
  def create
    return redirect_to(controls_url) unless @current_user.organization.nil?

    saved = false

    Organization.transaction do
      @organization = Organization.new(organization_params)
      @current_user.organization = @organization
      org_saved = @organization.save!
      user_saved = @current_user.save!
      saved = org_saved && user_saved
    end

    respond_to do |format|
      if saved
        format.html do
          redirect_to controls_url,
                      notice: 'Organization was successfully created.'
        end
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json do
          render json: @organization.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html do
          redirect_to @organization,
                      notice: 'Organization was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json do
          render json: @organization.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html do
        redirect_to organizations_url,
                    notice: 'Organization was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private # Use callbacks to share common setup or constraints between actions.
  def set_organization
    @organization = Organization.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def organization_params
    params.fetch(:organization, {}).permit(:name)
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper; end

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation" class="error-box">
      <h2 class="error-box__title"><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul class="error-box__list">
        <% organization.errors.full_messages.each do |message| %>
          <li class="error-box__list-item"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="stack-v">
    <div class="form-group">
      <%= label_tag :name, 'Your organization\'s name', class: 'form-group__label' %>
      <%= form.text_field :name, class: 'form-input', placeholder: 'e.g. Acme Co' %>
    </div>

    <div class="form-group__actions">
      <%= form.submit class: 'btn-primary form-group__action_item' %>
    </div>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/new.html.erb
<p id="notice" class="success-box"><%= notice %></p>

<div class="page-form">
  <div class="page-form__intro">
    <h1 class="text-white text-2xl mt-12">Your Organization</h1>
  </div>
  <%= render 'form', organization: @organization %>
</div>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>